# deploy aws-auth resource to give users access to the cluster      
# give permission to the github-ci profile to access EKS
# see chapter 31
# manual deployment : kubectl apply -f eks/aws-auth.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::354885450543:user/github-ci
      username: github-ci
      groups:
        - system:masters

