# Service defines the network to the outside world to the Pods
# Deploy: 'kubectl apply -f eks/service.yaml'
apiVersion: v1
kind: Service
metadata:
  name: simple-bank-api-service
spec:
  selector:
    app: simple-bank-api
  ports:
    - protocol: TCP
      port: 80            # external incoming request
      targetPort: 8080    # internal port of the container
#  type: LoadBalancer      # expose as a load balancer and external IP, to receive external requests (not by default)
#  type: ClusterIP         # this service will not be exposed to outside world and will not have external IP
#  type: NodePort