version: '3'

services:

  mainapp:
    build:
      context: ./../
      dockerfile: main-service.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=root password=secret dbname=simple_bank sslmode=disable timezone=UTC connect_timeout=5"
    depends_on:
      postgres:
        condition: service_started      

  postgres:
    container_name: 'postgres12'
    image: 'postgres:12-alpine'
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: simple_bank
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
