version: '3'

services:

  postgres:
    # container_name: 'postgres12'
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  api:
    build: 
      context: ../
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    restart: always    
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      postgres:
        condition: service_started

