version: '3'

services:

  postgres:
    container_name: postgres
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
    ports:
      - "5432:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
  
  redis:
    container_name: redis
    image: redis:7-alpine
    ports: 
      - '6379:6379'
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    volumes: 
      - ./db-data/radis/:/data

  # api:
  #   build: 
  #     context: ../
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
  #   restart: always    
  #   deploy:
  #     mode: replicated
  #     replicas: 1
  #   depends_on:
  #     postgres:
  #       condition: service_started

