---
name: Build and Push Golang Image to AWS ECR
on:
  push:
    branches: [ main ]
    
jobs:
  build-and-push:                 # deploy
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
    # checkout the code to the runner
    - name: Checkout repo into Go module directory
      uses: actions/checkout@v2

    # Install kubectl binary on the runner
    - name: Install Kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
      id: install

    # set login credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    # login to ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # load env variables from SecretsManager, format the result and populate the app.env file before building the image
    - name: Load secrets and save to app.env
      run: aws secretsmanager get-secret-value --region eu-central-1 --secret-id simple_bank --query SecretString --output text | jq -r 'to_entries|map("\(.key)=\(.value)")|.[]' > app.env

    # build docker image and push to ecr
    - name: Build, Tag, and Push the Image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: simplebank
        IMAGE_TAG: ${{ github.sha }}
      run: |        # | : run multiple commands
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t latest .
        docker push -a $ECR_REGISTRY/$ECR_REPOSITORY

#     - name: Deploy image to EKS
#       run: |
# # deploy aws-auth resource to give users access to the cluster      
#         kubectl apply -f eks/aws-auth.yaml 
# # deploy deployment resource to deploy the 'latest' container version
#         kubectl apply -f eks/deployment.yaml
# # deploy service resource to deploy service to the cluster
#         kubectl apply -f eks/service.yaml
# # deploy issuer resource to manage the TLS certificate
#         kubectl apply -f eks/issuer.yaml
# # deploy ingress resource to define the routing rules to the internal simple-bank service
#         kubectl apply -f eks/ingress.yaml